[tool.poetry]
name = "how-to-test-in-python"
version = "0.1.0"
description = ""
authors = ["xjr1300.04 <xjr1300.04@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
